### ISSUE TITLE
`require': cannot load such file -- guard/rspec_defaults (LoadError)

### ISSUE THREAD

**Issue by 1v** [guard/guard-rspec#352] opened 2016-01-04 18:19 UTC
I'm using Guard for gem testing without requiring it in gemspec and getting error:

```
/home/luna/.rvm/gems/ruby-2.3.0/gems/guard-rspec-4.6.4/lib/guard/rspec_formatter.rb:10:in `require': cannot load such file -- guard/rspec_defaults (LoadError)
	from /home/luna/.rvm/gems/ruby-2.3.0/gems/guard-rspec-4.6.4/lib/guard/rspec_formatter.rb:10:in `<top (required)>'
	from /home/luna/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1280:in `require'
	from /home/luna/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1280:in `block in requires='
	from /home/luna/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1280:in `each'
	from /home/luna/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1280:in `requires='
	from /home/luna/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration_options.rb:109:in `block in process_options_into'
	from /home/luna/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration_options.rb:108:in `each'
	from /home/luna/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration_options.rb:108:in `process_options_into'
	from /home/luna/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration_options.rb:21:in `configure'
	from /home/luna/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:101:in `setup'
	from /home/luna/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:88:in `run'
	from /home/luna/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:73:in `run'
	from /home/luna/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:41:in `invoke'
	from /home/luna/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.3.2/exe/rspec:4:in `<top (required)>'
	from /home/luna/.rvm/gems/ruby-2.3.0/bin/rspec:23:in `load'
	from /home/luna/.rvm/gems/ruby-2.3.0/bin/rspec:23:in `<main>'
	from /home/luna/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /home/luna/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

I think [`require "guard/rspec_defaults"`](https://github.com/guard/guard-rspec/blob/1a2cda48b15ea2759ba0421c333a2b25823c7879/lib/guard/rspec_formatter.rb#L10) need to be changed to `require_relative "rspec_defaults"`

**Comment by e2** [comment] 2016-01-04 20:26
Does it work? You can submit a PR.

Or you can create a repository reproducing the problem.

That part of the code is a bit brittle and hard to test, so I'd like to reproduce the problem first.

**Comment by 1v** [comment] 2016-01-04 23:05
```
git clone https://github.com/1v/torckapi.git && cd torckapi
```
Guardfile:
```
guard :rspec, cmd: "bundle exec rspec" do
  watch(%r{^spec/.+_spec\.rb$})
  watch(%r{^lib/(.+)\.rb$}) { "spec" } #     { |m| "spec/lib/#{m[1]}_spec.rb" }
  watch('spec/spec_helper.rb')  { "spec" }
end
```

**Comment by e2** [comment] 2016-01-06 02:32
Thanks! I wouldn't have been able to reproduce it without the repository (because I have shell aliases linking to bundler).

This will be fixed here: https://github.com/guard/guard-rspec/pull/354

**Closed** 2016-01-06 03:51 UTC
