### ISSUE TITLE
all_after_pass: true does not run all specs even if failed one's just passed

### ISSUE THREAD

**Issue by dima4p** [guard/guard-rspec#233] opened 2013-12-23 20:45 UTC
kubuntu 12.04LTS guard (2.2.4) rails (4.0.1) does not run all specs even if failed one's just passed

**Comment by e2** [comment] 2015-06-12 03:13
I'm closing this because it seems old.

If you have problems with the newest version of Guard::RSpec, please open a new issue with an example Guardfile and/or spec file to reproduce if you can.

**Closed by e2** 2015-06-12 03:13 UTC
