### ISSUE TITLE
No such file or directory @ rb_sysopen - tmp/rspec_guard_result with a syntax error

### ISSUE THREAD

**Issue by dima4p** [guard/guard-rspec#362] opened 2016-03-16 09:53 UTC
In the case of syntax error in the code RSpecProcess does not create formatter_tmp_file, so Guard::RSpec::Results.new generates an exception and guard fails.
 
Sorry, I can not now create PR, but the problem is fixed by writing the line results.rb#11 as follow:
lines = File.readlines(filename) rescue ['Syntax error']

**Comment by e2** [comment] 2016-03-16 20:35
Can you at least hint what kind of syntax error causes this? 
(Not every syntax errors results in this error).

Also, the fix needs to be handled at a higher level (I have an idea for this, but I need to reproduce this).

I can't accept this fix due to:

1. Other file related errors are hidden
2. Silencing the errors with no details of what failed (Generic `rescue` statements like this were used before - and they caused extremely hard to debug problems)

I can't reproduce this problem. The syntax errors I come up with just show up as syntax errors.

**Comment by dima4p** [comment] 2016-03-16 20:39
yes, in a model
`validates :name, presence: tru`

**Comment by dima4p** [comment] 2016-03-16 20:41
I agree, that higher level is better ;-)

**Comment by e2** [comment] 2016-03-16 21:04
I can't reproduce this. 

I'm correctly getting: `undefined local variable or method 'tru' for #<Class:0x000000062e0b98> (NameError)`

It may depend how model classes are loaded, rails version, spring, etc.

**Comment by ryan2johnson9** [comment] 2016-05-06 03:13
thanks dima4p for getting me back up and running, even if it is not ideal..
I got this error after changing back to MRI-2.3 from rbx-2.5.7
in case it helps
I'm running 

spring-1.7.1
guard-2.13.0
guard-rspec-4.6.5
rspec-3.4.0
rspec-rails-3.4.2
rails-4.1.6

**Comment by e2** [comment] 2016-05-06 04:02
Gosh, I'd be happy to fix this quickly (and release a fix) if I could only reproduce this.

Could someone copy a failing project, remove all unnecessary files, and upload it as a repo so I can reproduce this and take a look?

**Comment by dima4p** [comment] 2016-05-20 10:35
Please, try to run with Spork. I meet this problem in the projects that use it.

**Comment by e2** [comment] 2016-05-20 18:59
@dima4p - could you create a small repo to reproduce the problem so I can work on this?

If someone invests a bit of time into creating and sharing a repo with the issue, I'll invest some time into fixing this and releasing a fixed version.

(I've been debugging similar issues with Zeus and it's just too easy get mixed up - so an example repository is very, very helpful).

**Comment by e2** [comment] 2016-05-22 05:08
I've released v4.7.0 with extensive debugging to help resolve the issue.

So I'll close this. If it still occurs: 

1. Open a new issue
2. Attach the full info from `bundle exec guard -d`.

**Closed by e2** 2016-05-22 05:08 UTC
Labels: info needed

**Comment by ryan2johnson9** [comment] 2016-05-22 23:28
Thanks @e2 I will give it a try when I can. I did try to get a simple project going to illustrate the error, but could not reproduce it. Made me think it was some kind of syntactical issue within one of my many specs in the problematic project. I tried systematically commenting out specs and simplifying my guardfile but ALAS, the error did not go away.

**Comment by e2** [comment] 2016-05-23 02:43
With the new guard-rspec release and running under `bundle exec guard
-d`, the output alone should be enough for me to know what's going on.

Hope that helps nails this.

**Comment by ryan2johnson9** [comment] 2016-07-05 03:43
I updated to 4.7.2 and I no longer get the error. Thanks. sorry it took me so long.

**Comment by e2** [comment] 2016-07-29 16:48
Glad you have it work. Thanks for reporting.
